# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/ROM.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/RegisterFile.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/PCAddImm.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/PCAddFour.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/PC.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/NextPCSelect.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/Extend.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/DataSelect_5_bit.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/DataSelect_32_bit.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/DataSelectForALU.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/DataMemory.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/ControlUnit.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/ALU.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/SingleCPU.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/SegLED.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/Display_seg.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/DebKey.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/counter4.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/clock_div.v
  F:/VivadoWork/Single_CPU/Single_CPU.srcs/sources_1/new/Show.v
}
read_xdc F:/VivadoWork/Single_CPU/Single_CPU.srcs/constrs_1/new/Single_CPU.xdc
set_property used_in_implementation false [get_files F:/VivadoWork/Single_CPU/Single_CPU.srcs/constrs_1/new/Single_CPU.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/VivadoWork/Single_CPU/Single_CPU.cache/wt [current_project]
set_property parent.project_dir F:/VivadoWork/Single_CPU [current_project]
catch { write_hwdef -file Show.hwdef }
synth_design -top Show -part xc7a35tcpg236-1
write_checkpoint Show.dcp
report_utilization -file Show_utilization_synth.rpt -pb Show_utilization_synth.pb
